# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rik.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fyysilineIsik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isikukood', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, 'Isikukood peab sisaldama ühtteist numbrit; hetkel on %(show_value)d.'), django.core.validators.RegexValidator('^[0-9]*$', 'Lubatud ainult numbrid!')])),
                ('eesnimi', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZäöüõÄÖÕÜ\\-]*$', 'Lubatud ainult tähed!')])),
                ('perenimi', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZäöüõÄÖÕÜ\\-]*$', 'Lubatud ainult tähed!')])),
            ],
        ),
        migrations.CreateModel(
            name='juriidilineIsik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regkood', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7, 'Registrikood peab sisaldama seitset numbrit; hetkel on %(show_value)d.'), django.core.validators.RegexValidator('^[0-9]*$', 'Lubatud ainult numbrid!')])),
                ('nimi', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Nimi peab sisaldama vähemalt kolme tähte ja/või numbrit; hetkel on %(show_value)d.'), django.core.validators.RegexValidator('^[a-zA-Z0-9_äöüõÄÖÕÜ\\- ]*$', 'Lubatud ainult tähed ja numbrid!')])),
            ],
        ),
        migrations.CreateModel(
            name='osanik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osakapital', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Osakapitali suurus peab olema vähemalt 1 eurot.')])),
                ('asutaja', models.BooleanField(default=True)),
                ('fyysilineIsik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rik.fyysilineIsik')),
                ('juriidilineIsik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rik.juriidilineIsik')),
            ],
        ),
        migrations.CreateModel(
            name='osayhing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regkood', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7, 'Registrikood peab sisaldama seitset numbrit; hetkel on %(show_value)d.'), django.core.validators.RegexValidator('^[0-9]*$', 'Lubatud ainult numbrid!')])),
                ('nimi', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Nimi peab sisaldama vähemalt kolme tähte ja/või numbrit; hetkel on %(show_value)d.'), django.core.validators.RegexValidator('^[a-zA-Z0-9_äöüõÄÖÕÜ\\- ]*$', 'Lubatud ainult tähed ja numbrid!')])),
                ('asutamiskp', models.DateField(validators=[rik.utils.validateDate])),
                ('kogukapital', models.IntegerField(validators=[django.core.validators.MinValueValidator(2500, 'Kogukapitali suurus peab olema vähemalt 2500 eurot.')])),
            ],
        ),
        migrations.AddField(
            model_name='osanik',
            name='osayhing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rik.osayhing'),
        ),
    ]
